#Sys.setenv(RSTUDIO_PANDOC="/usr/lib/rstudio-server/bin/pandoc")
#print("tucośpowinnobyć")
library(here)
library(usethis)
library(gitcreds)
rmarkdown::render(input=here("./ignacymorawski.github.io/index.Rmd"), output_file=here("./ignacymorawski.github.io/index.html"))
setwd("C:/Users/j.morawski/Documents/ignacymorawski/ignacymorawski.github.io")
system("git add -all")
system(paste0("git commit -m \"",Sys.time(),"\""))
system("git push -u origin main")
setwd("C:/Users/j.morawski/Documents/ignacymorawski")
#source("C:/Users/i.morawski/Documents/forecast/UpdateGitHub.R")
#setwd("C:/Users/i.morawski/Documents/forecast/PulsBiznesu")
#UpdateGitHub()

